//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TicketAspNetMVC.TicketServiceReference {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="TicketServiceReference.ITicketWCF")]
    public interface ITicketWCF {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicketWCF/GetData", ReplyAction="http://tempuri.org/ITicketWCF/GetDataResponse")]
        System.Collections.Generic.Dictionary<string, string>[] GetData(string Storeprocedure, string id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ITicketWCF/GetData", ReplyAction="http://tempuri.org/ITicketWCF/GetDataResponse")]
        System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>[]> GetDataAsync(string Storeprocedure, string id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ITicketWCFChannel : TicketAspNetMVC.TicketServiceReference.ITicketWCF, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TicketWCFClient : System.ServiceModel.ClientBase<TicketAspNetMVC.TicketServiceReference.ITicketWCF>, TicketAspNetMVC.TicketServiceReference.ITicketWCF {
        
        public TicketWCFClient() {
        }
        
        public TicketWCFClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TicketWCFClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TicketWCFClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TicketWCFClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Collections.Generic.Dictionary<string, string>[] GetData(string Storeprocedure, string id) {
            return base.Channel.GetData(Storeprocedure, id);
        }
        
        public System.Threading.Tasks.Task<System.Collections.Generic.Dictionary<string, string>[]> GetDataAsync(string Storeprocedure, string id) {
            return base.Channel.GetDataAsync(Storeprocedure, id);
        }
    }
}
